/**
 * PATCH /api/admin/producers/[id]
 * Gestion d'une fiche producteur / beatmaker créée automatiquement :
 * changement de type, validation (sortie du mode auto-généré), désactivation.
 */
import { NextResponse } from "next/server";
import { requireAdmin } from "@/lib/auth/admin-guard";
import { createAdminClient } from "@/lib/supabase/admin";

export const dynamic = "force-dynamic";

const ARTIST_TYPES = new Set([
  "artist",
  "group",
  "producer",
  "beatmaker",
  "dj",
  "musician",
  "singer",
  "rapper",
]);

export async function PATCH(request: Request, { params }: { params: Promise<{ id: string }> }) {
  const auth = await requireAdmin();
  if (!auth.ok) return NextResponse.json({ error: auth.error }, { status: auth.status });

  const { id } = await params;
  const body = await request.json().catch(() => null);
  if (!body || typeof body !== "object") {
    return NextResponse.json({ error: "Corps invalide." }, { status: 400 });
  }

  const input = body as Record<string, unknown>;
  const patch: Record<string, unknown> = {};

  if ("artistType" in input) {
    const type = String(input.artistType);
    if (!ARTIST_TYPES.has(type)) {
      return NextResponse.json({ error: "Type d'artiste inconnu." }, { status: 400 });
    }
    patch.artist_type = type;
  }

  // « Valider » = le profil n'est plus considéré comme auto-généré et
  // réapparaît dans la grille générale si son statut haïtien le permet.
  if ("isAutoGenerated" in input) {
    if (typeof input.isAutoGenerated !== "boolean") {
      return NextResponse.json({ error: "isAutoGenerated doit être un booléen." }, { status: 400 });
    }
    patch.is_auto_generated = input.isAutoGenerated;
  }

  if ("isActive" in input) {
    if (typeof input.isActive !== "boolean") {
      return NextResponse.json({ error: "isActive doit être un booléen." }, { status: 400 });
    }
    patch.is_active = input.isActive;
  }

  if (Object.keys(patch).length === 0) {
    return NextResponse.json({ error: "Aucun champ à mettre à jour." }, { status: 400 });
  }

  patch.updated_at = new Date().toISOString();

  const supabase = createAdminClient();
  const { error } = await supabase.from("artists").update(patch).eq("id", id);
  if (error) return NextResponse.json({ error: error.message }, { status: 500 });

  return NextResponse.json({ ok: true });
}
