import { redirect } from "next/navigation";
import { getAdminUser } from "@/lib/auth/admin-guard";
import { createAdminClient } from "@/lib/supabase/admin";
import { AdminHeader } from "../AdminHeader";
import { ProducersManager, type AdminProducer, type AdminProduction } from "./ProducersManager";
import { isSpotifyConfigured } from "@/lib/spotify/api-client";

export const dynamic = "force-dynamic";

export default async function AdminProducteursPage() {
  const user = await getAdminUser();
  if (!user) redirect("/admin/login?next=/admin/producteurs");

  const supabase = createAdminClient();

  const [{ data: producers }, { data: productions }, { count: missingPhotos }] = await Promise.all([
    supabase
      .from("artists")
      .select("id, name, slug, image_url, artist_type, is_active, is_auto_generated, haitian_status, url_spotify, spotify_producer_id")
      .in("artist_type", ["producer", "beatmaker"])
      .order("name")
      .limit(500),
    supabase
      .from("artist_productions")
      .select(
        "id, producer_id, track_id, role, credit_source, credit_note, confidence, is_verified, created_at, tracks(title)",
      )
      .order("created_at", { ascending: false })
      .limit(1000),
    supabase
      .from("artists")
      .select("id", { count: "exact", head: true })
      .or("image_url.is.null,image_url.eq."),
  ]);

  const productionRows: AdminProduction[] = (productions ?? []).map((row) => {
    const track = Array.isArray(row.tracks) ? row.tracks[0] : row.tracks;
    return {
      id: row.id as string,
      producerId: row.producer_id as string,
      trackId: row.track_id as string,
      trackTitle: (track as { title?: string } | null)?.title ?? "Sans titre",
      role: (row.role as string) ?? "producer",
      creditSource: (row.credit_source as string) ?? "manual_admin",
      creditNote: (row.credit_note as string) ?? null,
      confidence: Number(row.confidence ?? 1),
      isVerified: !!row.is_verified,
    };
  });

  const producerRows: AdminProducer[] = (producers ?? []).map((row) => ({
    id: row.id as string,
    name: row.name as string,
    slug: row.slug as string,
    imageUrl: (row.image_url as string) ?? null,
    artistType: (row.artist_type as string) ?? "producer",
    isActive: !!row.is_active,
    isAutoGenerated: !!row.is_auto_generated,
    haitianStatus: (row.haitian_status as string) ?? "pending_review",
    spotifyUrl: (row.url_spotify as string) ?? null,
    productionCount: productionRows.filter((p) => p.producerId === row.id).length,
  }));

  return (
    <>
      <AdminHeader email={user.email} active="producteurs" />
      <main className="admin__main">
        <h1 className="admin__title">Producteurs &amp; Beatmakers</h1>
        <p className="admin__subtitle">
          Synchronisez les crédits de production, validez les fiches créées automatiquement
          et complétez les photos de profil manquantes depuis les plateformes.
        </p>
        <ProducersManager
          producers={producerRows}
          productions={productionRows}
          spotifyConfigured={isSpotifyConfigured()}
          missingPhotoCount={missingPhotos ?? 0}
        />
      </main>
    </>
  );
}
