"use client";
/* eslint-disable @next/next/no-img-element -- portraits distants (Spotify, YouTube) */

import { useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import {
  CollectProgressBar,
  readCollectStream,
  type CollectProgress,
} from "@/components/CollectProgressBar";
import { artistAvatarSrc } from "@/lib/artists/avatar";
import { CREDIT_SOURCE_LABELS, PRODUCTION_ROLE_LABELS } from "@/lib/producers/queries";
import styles from "./producteurs.module.css";

export interface AdminProducer {
  id: string;
  name: string;
  slug: string;
  imageUrl: string | null;
  artistType: string;
  isActive: boolean;
  isAutoGenerated: boolean;
  haitianStatus: string;
  spotifyUrl: string | null;
  productionCount: number;
}

export interface AdminProduction {
  id: string;
  producerId: string;
  trackId: string;
  trackTitle: string;
  role: string;
  creditSource: string;
  creditNote: string | null;
  confidence: number;
  isVerified: boolean;
}

type Tone = "success" | "warning" | "error";
type Filter = "all" | "auto" | "validated" | "unverified_credits";

const FILTERS: { id: Filter; label: string }[] = [
  { id: "all", label: "Tous" },
  { id: "auto", label: "Créés automatiquement" },
  { id: "validated", label: "Validés" },
  { id: "unverified_credits", label: "Crédits à confirmer" },
];

export function ProducersManager({
  producers,
  productions,
  spotifyConfigured,
  missingPhotoCount,
}: {
  producers: AdminProducer[];
  productions: AdminProduction[];
  spotifyConfigured: boolean;
  missingPhotoCount: number;
}) {
  const router = useRouter();
  const [progress, setProgress] = useState<CollectProgress | null>(null);
  const [busy, setBusy] = useState<string | null>(null);
  const [message, setMessage] = useState<{ text: string; tone: Tone } | null>(null);
  const [filter, setFilter] = useState<Filter>("all");
  const [search, setSearch] = useState("");
  const [expanded, setExpanded] = useState<string | null>(null);
  const [trackLimit, setTrackLimit] = useState("500");
  const [enrichSpotify, setEnrichSpotify] = useState(true);

  const productionsByProducer = useMemo(() => {
    const map = new Map<string, AdminProduction[]>();
    for (const production of productions) {
      const list = map.get(production.producerId) ?? [];
      list.push(production);
      map.set(production.producerId, list);
    }
    return map;
  }, [productions]);

  const filtered = useMemo(() => {
    const query = search.trim().toLowerCase();
    return producers.filter((producer) => {
      if (query && !producer.name.toLowerCase().includes(query)) return false;
      if (filter === "auto") return producer.isAutoGenerated;
      if (filter === "validated") return !producer.isAutoGenerated;
      if (filter === "unverified_credits") {
        return (productionsByProducer.get(producer.id) ?? []).some((p) => !p.isVerified);
      }
      return true;
    });
  }, [producers, search, filter, productionsByProducer]);

  const unverifiedCount = productions.filter((p) => !p.isVerified).length;

  async function runSync() {
    setBusy("sync");
    setMessage(null);
    setProgress({ phase: "init", percent: 0, message: "Démarrage de la synchronisation..." });
    try {
      const response = await fetch("/api/admin/producers/sync", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          trackLimit: Number(trackLimit) || 500,
          enrichWithSpotify: enrichSpotify,
        }),
      });

      if (!response.ok && response.headers.get("Content-Type")?.includes("json")) {
        const json = await response.json();
        setProgress({ phase: "error", percent: 0, message: json.error ?? "Erreur." });
        return;
      }

      const last = await readCollectStream(response, setProgress);
      if (last?.phase === "done") router.refresh();
    } catch {
      setProgress({ phase: "error", percent: 0, message: "Erreur réseau." });
    } finally {
      setBusy(null);
    }
  }

  async function backfillImages() {
    setBusy("images");
    setMessage(null);
    try {
      const response = await fetch("/api/admin/artistes/backfill-images", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ limit: 1000 }),
      });
      const json = await response.json();
      setMessage({
        text: json.error ?? json.message,
        tone: response.ok ? (json.updated > 0 ? "success" : "warning") : "error",
      });
      if (response.ok) router.refresh();
    } catch {
      setMessage({ text: "Erreur réseau.", tone: "error" });
    } finally {
      setBusy(null);
    }
  }

  async function patchProducer(id: string, patch: Record<string, unknown>, label: string) {
    setBusy(id);
    setMessage(null);
    try {
      const response = await fetch(`/api/admin/producers/${id}`, {
        method: "PATCH",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(patch),
      });
      const json = await response.json();
      setMessage({
        text: response.ok ? label : (json.error ?? "Erreur."),
        tone: response.ok ? "success" : "error",
      });
      if (response.ok) router.refresh();
    } catch {
      setMessage({ text: "Erreur réseau.", tone: "error" });
    } finally {
      setBusy(null);
    }
  }

  async function setCreditVerified(productionId: string, isVerified: boolean) {
    setBusy(productionId);
    setMessage(null);
    try {
      const response = await fetch("/api/admin/producers/productions", {
        method: "PATCH",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ productionId, isVerified }),
      });
      const json = await response.json();
      setMessage({
        text: response.ok
          ? isVerified
            ? "Crédit confirmé."
            : "Crédit remis en attente."
          : (json.error ?? "Erreur."),
        tone: response.ok ? "success" : "error",
      });
      if (response.ok) router.refresh();
    } catch {
      setMessage({ text: "Erreur réseau.", tone: "error" });
    } finally {
      setBusy(null);
    }
  }

  async function deleteCredit(productionId: string, trackTitle: string) {
    if (!confirm(`Supprimer le crédit sur « ${trackTitle} » ?`)) return;
    setBusy(productionId);
    setMessage(null);
    try {
      const response = await fetch(
        `/api/admin/producers/productions?productionId=${encodeURIComponent(productionId)}`,
        { method: "DELETE" },
      );
      const json = await response.json();
      setMessage({
        text: response.ok ? "Crédit supprimé." : (json.error ?? "Erreur."),
        tone: response.ok ? "success" : "error",
      });
      if (response.ok) router.refresh();
    } catch {
      setMessage({ text: "Erreur réseau.", tone: "error" });
    } finally {
      setBusy(null);
    }
  }

  return (
    <>
      {/* Panneau de synchronisation */}
      <section className="admin-card" style={{ marginBottom: "1.2rem" }}>
        <h2 className="admin-card__title">Synchronisation des crédits</h2>
        <p style={{ color: "var(--admin-muted)", fontSize: "0.82rem", marginTop: 0 }}>
          Les crédits sont lus dans les mentions « Prod. by » publiées sur les titres
          (la Web API Spotify n&apos;expose aucun endpoint de crédits). Chaque producteur
          détecté obtient une fiche, puis son profil Spotify est recherché pour récupérer
          portrait, lien et identifiant.
        </p>

        <div style={{ display: "flex", flexWrap: "wrap", gap: "0.8rem", alignItems: "flex-end" }}>
          <label style={{ display: "flex", flexDirection: "column", gap: "0.25rem" }}>
            <span style={{ fontSize: "0.78rem", color: "var(--admin-muted)" }}>
              Chansons à analyser
            </span>
            <input
              type="number"
              min={1}
              max={5000}
              value={trackLimit}
              onChange={(e) => setTrackLimit(e.target.value)}
              className={styles.input}
              style={{ width: 120 }}
            />
          </label>

          <label
            style={{ display: "flex", gap: "0.4rem", alignItems: "center", fontSize: "0.82rem" }}
          >
            <input
              type="checkbox"
              checked={enrichSpotify}
              disabled={!spotifyConfigured}
              onChange={(e) => setEnrichSpotify(e.target.checked)}
            />
            Enrichir via Spotify
          </label>

          <button
            type="button"
            className="btn btn--primary"
            onClick={runSync}
            disabled={busy !== null}
          >
            {busy === "sync" ? "Synchronisation…" : "Lancer la synchronisation"}
          </button>

          <button
            type="button"
            className="btn btn--ghost"
            onClick={backfillImages}
            disabled={busy !== null}
            title="Reprend la photo d'une plateforme rattachée pour les fiches sans photo"
          >
            {busy === "images"
              ? "Complétion…"
              : `Compléter les photos manquantes (${missingPhotoCount})`}
          </button>
        </div>

        {!spotifyConfigured && (
          <p style={{ color: "var(--admin-warn)", fontSize: "0.78rem", marginBottom: 0 }}>
            ⚠ SPOTIFY_CLIENT_ID / SPOTIFY_CLIENT_SECRET absents : l&apos;enrichissement est
            désactivé. Les crédits seront quand même extraits des titres.
          </p>
        )}

        <CollectProgressBar progress={progress} />

        {message && (
          <p
            style={{
              marginTop: "0.8rem",
              marginBottom: 0,
              fontSize: "0.82rem",
              color:
                message.tone === "error"
                  ? "var(--admin-danger)"
                  : message.tone === "warning"
                    ? "var(--admin-warn)"
                    : "var(--admin-ok)",
            }}
            role="status"
          >
            {message.text}
          </p>
        )}
      </section>

      {/* Liste des producteurs */}
      <section className="admin-card">
        <h2 className="admin-card__title">
          {producers.length} fiche(s) producteur · {productions.length} crédit(s)
          {unverifiedCount > 0 && ` · ${unverifiedCount} à confirmer`}
        </h2>

        <div
          style={{
            display: "flex",
            flexWrap: "wrap",
            gap: "0.5rem",
            alignItems: "center",
            marginBottom: "1rem",
          }}
        >
          <input
            type="search"
            placeholder="Rechercher un producteur…"
            aria-label="Rechercher un producteur"
            value={search}
            onChange={(e) => setSearch(e.target.value)}
            className={styles.input}
            style={{ maxWidth: 260 }}
          />
          {FILTERS.map((f) => (
            <button
              key={f.id}
              type="button"
              className={filter === f.id ? "btn btn--sm btn--primary" : "btn btn--sm btn--ghost"}
              onClick={() => setFilter(f.id)}
            >
              {f.label}
            </button>
          ))}
        </div>

        {filtered.length === 0 ? (
          <p style={{ color: "var(--admin-muted)", fontSize: "0.85rem" }}>
            Aucune fiche pour ces critères. Lancez une synchronisation pour détecter les
            producteurs crédités dans les titres.
          </p>
        ) : (
          <ul style={{ listStyle: "none", margin: 0, padding: 0, display: "grid", gap: "0.5rem" }}>
            {filtered.map((producer) => {
              const rows = productionsByProducer.get(producer.id) ?? [];
              const isOpen = expanded === producer.id;
              return (
                <li
                  key={producer.id}
                  style={{
                    border: "1px solid var(--admin-border)",
                    borderRadius: 10,
                    background: "var(--admin-panel-2)",
                    padding: "0.7rem 0.9rem",
                  }}
                >
                  <div
                    style={{
                      display: "flex",
                      gap: "0.8rem",
                      alignItems: "center",
                      flexWrap: "wrap",
                    }}
                  >
                    <img
                      src={artistAvatarSrc(producer.imageUrl)}
                      alt=""
                      width={44}
                      height={44}
                      style={{ borderRadius: "50%", objectFit: "cover", flexShrink: 0 }}
                    />
                    <div style={{ flex: 1, minWidth: 160 }}>
                      <strong style={{ fontSize: "0.9rem" }}>{producer.name}</strong>
                      <p
                        style={{
                          margin: 0,
                          fontSize: "0.75rem",
                          color: "var(--admin-muted)",
                        }}
                      >
                        {PRODUCTION_ROLE_LABELS[producer.artistType] ?? producer.artistType} ·{" "}
                        {producer.productionCount} titre
                        {producer.productionCount > 1 ? "s" : ""}
                        {producer.isAutoGenerated && " · créé automatiquement"}
                        {!producer.isActive && " · désactivé"}
                      </p>
                    </div>

                    <select
                      value={producer.artistType}
                      aria-label={`Type de ${producer.name}`}
                      onChange={(e) =>
                        patchProducer(
                          producer.id,
                          { artistType: e.target.value },
                          "Type mis à jour.",
                        )
                      }
                      disabled={busy !== null}
                      className={styles.input}
                      style={{ width: 140 }}
                    >
                      <option value="producer">Producteur</option>
                      <option value="beatmaker">Beatmaker</option>
                      <option value="artist">Artiste (solo)</option>
                      <option value="dj">DJ</option>
                      <option value="musician">Musicien</option>
                    </select>

                    {producer.isAutoGenerated ? (
                      <button
                        type="button"
                        className="btn btn--sm btn--primary"
                        disabled={busy !== null}
                        onClick={() =>
                          patchProducer(
                            producer.id,
                            { isAutoGenerated: false },
                            "Fiche validée : elle peut désormais apparaître dans la grille générale.",
                          )
                        }
                        title="La fiche quitte le mode automatique et redevient éligible à la grille générale"
                      >
                        Valider la fiche
                      </button>
                    ) : (
                      <span style={{ fontSize: "0.75rem", color: "var(--admin-ok)" }}>
                        ✓ validée
                      </span>
                    )}

                    <button
                      type="button"
                      className="btn btn--sm btn--ghost"
                      disabled={busy !== null}
                      onClick={() =>
                        patchProducer(
                          producer.id,
                          { isActive: !producer.isActive },
                          producer.isActive ? "Fiche désactivée." : "Fiche réactivée.",
                        )
                      }
                    >
                      {producer.isActive ? "Désactiver" : "Réactiver"}
                    </button>

                    <a
                      href={`/admin/artistes/${producer.id}`}
                      className="btn btn--sm btn--ghost"
                    >
                      Fiche complète
                    </a>

                    <button
                      type="button"
                      className="btn btn--sm btn--ghost"
                      onClick={() => setExpanded(isOpen ? null : producer.id)}
                      aria-expanded={isOpen}
                    >
                      {isOpen ? "Masquer" : `Crédits (${rows.length})`}
                    </button>
                  </div>

                  {isOpen && (
                    <div style={{ marginTop: "0.7rem" }}>
                      {rows.length === 0 ? (
                        <p style={{ fontSize: "0.8rem", color: "var(--admin-muted)", margin: 0 }}>
                          Aucun crédit rattaché.
                        </p>
                      ) : (
                        <table className={styles.table}>
                          <thead>
                            <tr>
                              <th>Titre</th>
                              <th>Rôle</th>
                              <th>Origine</th>
                              <th>Confiance</th>
                              <th>Actions</th>
                            </tr>
                          </thead>
                          <tbody>
                            {rows.map((row) => (
                              <tr key={row.id}>
                                <td>
                                  {row.trackTitle}
                                  {row.creditNote && (
                                    <span
                                      style={{
                                        display: "block",
                                        fontSize: "0.72rem",
                                        color: "var(--admin-muted)",
                                      }}
                                    >
                                      {row.creditNote}
                                    </span>
                                  )}
                                </td>
                                <td>{PRODUCTION_ROLE_LABELS[row.role] ?? row.role}</td>
                                <td>{CREDIT_SOURCE_LABELS[row.creditSource] ?? row.creditSource}</td>
                                <td>{Math.round(row.confidence * 100)}%</td>
                                <td style={{ whiteSpace: "nowrap" }}>
                                  <button
                                    type="button"
                                    className="btn btn--sm btn--ghost"
                                    disabled={busy !== null}
                                    onClick={() => setCreditVerified(row.id, !row.isVerified)}
                                  >
                                    {row.isVerified ? "Remettre en attente" : "Confirmer"}
                                  </button>
                                  <button
                                    type="button"
                                    className="btn btn--sm btn--ghost"
                                    disabled={busy !== null}
                                    onClick={() => deleteCredit(row.id, row.trackTitle)}
                                    style={{ color: "var(--admin-danger)" }}
                                  >
                                    Supprimer
                                  </button>
                                </td>
                              </tr>
                            ))}
                          </tbody>
                        </table>
                      )}
                    </div>
                  )}
                </li>
              );
            })}
          </ul>
        )}
      </section>
    </>
  );
}
